org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens=java.base/java.lang=ALL-UNNAMED
android.useAndroidX=true
org.gradle.java.home=C\:\\Users\\yashw\\.gradle\\jdks\\eclipse_adoptium-21-amd64-windows.2
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=C\:\\Users\\yashw\\.gradle\\jdks\\eclipse_adoptium-21-amd64-windows.2
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
